baseURL = "https://robinwords.com/"
languageCode = "en-us"
title = "About"
theme = "hud"
sectionPagesMenu = "navmenu"

[menu]

  [[menu.navmenu]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/"

  [[menu.navmenu]]
    identifier = "game"
    name = "Game"
    title = "Game"
    url = "/game"
